const postName=document.querySelector('#postName');
const postSpace=document.querySelector('#postSpace');
const postText=document.querySelector('#postText');
const charCount=document.querySelector('#charCount');
const publishPost=document.querySelector('#publishPost');
const postError=document.querySelector('#postError');
const feedList=document.querySelector('#feedList');
const postCount=document.querySelector('#postCount');
const feedClock=document.querySelector('#feedClock');
const clearFeed=document.querySelector('#clearFeed');
const channels=document.querySelectorAll('.channel');
const storageKey='selestiaCommunityPosts';
let activeFilter='all';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
const starterPosts=[{id:uid(),name:'Selestia System',space:'General',text:'Welcome to the Community Feed. Create your first post and it will be saved locally in your browser.',likes:4,comments:[],createdAt:Date.now()-600000},{id:uid(),name:'Study Room',space:'Study',text:'Looking for a 25 minute focus partner? Drop your study topic here.',likes:2,comments:['I can join after lunch.'],createdAt:Date.now()-1800000}];
const loadPosts=()=>JSON.parse(localStorage.getItem(storageKey)||'null')||starterPosts;
const savePosts=(value)=>localStorage.setItem(storageKey,JSON.stringify(value));
let posts=loadPosts();
const timeAgo=(timestamp)=>{const seconds=Math.floor((Date.now()-timestamp)/1000);if(seconds<10)return 'just now';if(seconds<60)return seconds+'s ago';const minutes=Math.floor(seconds/60);if(minutes<60)return minutes+'m ago';const hours=Math.floor(minutes/60);if(hours<24)return hours+'h ago';return Math.floor(hours/24)+'d ago'};
const updateFeedClock=()=>{feedClock.textContent=new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit', second:'2-digit'});};
const initial=(name)=>(name||'S').slice(0,1).toUpperCase();
const esc=(text)=>String(text).replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const renderPosts=()=>{updateFeedClock();const visible=posts.filter((post)=>activeFilter==='all'||post.space===activeFilter);postCount.textContent=posts.length;if(!visible.length){feedList.innerHTML='<div class="empty-state">No posts in this channel yet. Create one above.</div>';return}feedList.innerHTML=visible.map((post)=>'<article class="post-card" data-id="'+post.id+'"><div class="post-top"><div class="post-author"><div class="post-avatar">'+initial(post.name)+'</div><div><strong>'+esc(post.name)+'</strong><div class="post-meta"><span class="post-space">'+esc(post.space)+'</span> • '+timeAgo(post.createdAt)+'</div></div></div><span class="post-time">'+new Date(post.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+'</span></div><div class="post-text">'+esc(post.text)+'</div><div class="post-actions"><button class="post-action" type="button" data-action="like">⚡ '+post.likes+' Boosts</button><button class="post-action" type="button" data-action="comment">💬 '+post.comments.length+' Comments</button><button class="post-action" type="button" data-action="delete">Delete</button></div><div class="comment-box"><input type="text" placeholder="Write a comment..." /><button class="post-action" type="button" data-action="send-comment">Send</button></div><div class="comments">'+post.comments.map((comment)=>'<div class="comment">'+esc(comment)+'</div>').join('')+'</div></article>').join('')};
const createPost=()=>{const text=postText.value.trim();const name=postName.value.trim()||'Selestia Member';if(text.length<3){postError.textContent='Write at least 3 characters before posting.';return}postError.textContent='';posts.unshift({id:uid(),name,space:postSpace.value,text,likes:0,comments:[],createdAt:Date.now()});postText.value='';charCount.textContent='0';savePosts(posts);renderPosts()};
postText.addEventListener('input',()=>{charCount.textContent=postText.value.length});
publishPost.addEventListener('click',createPost);
postText.addEventListener('keydown',(event)=>{if((event.metaKey||event.ctrlKey)&&event.key==='Enter')createPost()});
channels.forEach((channel)=>channel.addEventListener('click',()=>{activeFilter=channel.dataset.filter;channels.forEach((item)=>item.classList.toggle('active',item===channel));renderPosts()}));
feedList.addEventListener('click',(event)=>{const card=event.target.closest('.post-card');if(!card)return;const post=posts.find((item)=>item.id===card.dataset.id);if(!post)return;const action=event.target.dataset.action;if(action==='like')post.likes+=1;if(action==='delete')posts=posts.filter((item)=>item.id!==post.id);if(action==='comment')card.querySelector('.comment-box').classList.toggle('is-open');if(action==='send-comment'){const input=card.querySelector('.comment-box input');const comment=input.value.trim();if(comment)post.comments.push(comment);input.value=''}savePosts(posts);if(action!=='comment')renderPosts()});
clearFeed.addEventListener('click',()=>{posts=[];savePosts(posts);renderPosts()});
renderPosts();
setInterval(renderPosts, 60000);
setInterval(updateFeedClock, 1000);