const safeJson=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
const number=(key)=>Number(localStorage.getItem(key)||0);
const fmtMinutes=(seconds)=>{const minutes=Math.floor(seconds/60);if(minutes<60)return minutes+'m';const hours=Math.floor(minutes/60);return hours+'h '+(minutes%60)+'m'};
const calc=()=>{
  const gamingRawXp=number('selestiaXP');
  const gamingWins=number('selestiaWins');
  const focusSeconds=number('selestiaStudyFocusedSeconds');
  const focusMinutes=Math.floor(focusSeconds/60);
  const musicQueue=safeJson('selestiaMusicQueue').length;
  const musicPlaylists=safeJson('selestiaMusicPlaylists').length;
  const communityPosts=safeJson('selestiaCommunityPosts').length;
  const techXp=number('selestiaTechXP');
  const techProjects=safeJson('selestiaTechProjects').length;
  const techTasks=safeJson('selestiaTechTasks').filter((task)=>task.status==='done').length;
  const artXp=number('selestiaArtXP');
  const artCompleted=safeJson('selestiaArtCompleted').length;
  const musicXp=(musicQueue*3)+(musicPlaylists*15);
  const studyXp=focusMinutes*2;
  const communityXp=communityPosts*15;
  const totalXp=gamingRawXp+studyXp+musicXp+communityXp+techXp+artXp;
  const level=Math.floor(totalXp/100)+1;
  const levelXp=totalXp%100;
  return {gamingRawXp,gamingWins,focusSeconds,focusMinutes,musicQueue,musicPlaylists,communityPosts,techXp,techProjects,techTasks,artXp,artCompleted,musicXp,studyXp,communityXp,totalXp,level,levelXp};
};
const setText=(id,value)=>{document.querySelector('#'+id).textContent=value};
const getProfile=()=>{try{return JSON.parse(localStorage.getItem('selestiaProfile')||'null')}catch(error){return null}};
const showAuthNotice=()=>{const notice=document.querySelector('#dashboardAuthNotice');if(notice)notice.hidden=Boolean(getProfile())};
const renderProfile=()=>{
  let profile=getProfile()
  if(!profile)return;
  const orb=document.querySelector('#avatarOrb');
  const name=document.querySelector('#dashboardName');
  const bio=document.querySelector('#dashboardBio');
  if(orb)orb.textContent=profile.avatarIcon||'✦';
  if(name)name.textContent=profile.username||'Selestia Member';
  if(bio)bio.textContent=profile.bio||('Selected space: '+((profile.world||'selestia').charAt(0).toUpperCase()+(profile.world||'selestia').slice(1)));
};
const renderLocked=()=>{
  setText('levelText','--');
  setText('levelTitle','Login Required');
  setText('totalXpText','Login to sync XP');
  setText('nextLevelText','No live profile connected');
  document.querySelector('#xpFill').style.width='0%';
  setText('gamingWins','--');
  setText('focusTime','--');
  setText('communityPosts','--');
  setText('musicSaves','--');
  document.querySelector('#xpBreakdown').innerHTML=['Gaming XP','Study XP','Music XP','Community XP','Tech XP','Art XP'].map((label)=>'<div class="xp-row locked-stat"><span>'+label+'</span><strong>Login</strong></div>').join('');
  document.querySelector('#spaceActivity').innerHTML='<div class="space-row"><span>Login to connect live space activity.</span><strong>Locked</strong><meter min="0" max="100" value="0"></meter></div>';
  document.querySelector('#activityList').innerHTML='<div class="activity-row"><span>No live profile is connected yet.</span><strong>Locked</strong></div>';
};
const render=()=>{
  const profile=getProfile();
  showAuthNotice();
  document.body.classList.toggle('no-profile', !profile);
  if(!profile){renderLocked();return;}
  renderProfile();
  const data=calc();
  setText('levelText',data.level);
  setText('levelTitle',data.level<3?'New Explorer':data.level<6?'Rising Navigator':'Celestial Pro');
  setText('totalXpText',data.totalXp+' XP');
  setText('nextLevelText',(100-data.levelXp)+' XP to level '+(data.level+1));
  document.querySelector('#xpFill').style.width=data.levelXp+'%';
  setText('gamingWins',data.gamingWins);
  setText('focusTime',fmtMinutes(data.focusSeconds));
  setText('communityPosts',data.communityPosts);
  setText('musicSaves',data.musicQueue+data.musicPlaylists);
  document.querySelector('#xpBreakdown').innerHTML=[['Gaming XP',data.gamingRawXp],['Study XP',data.studyXp],['Music XP',data.musicXp],['Community XP',data.communityXp],['Tech XP',data.techXp],['Art XP',data.artXp]].map(([label,value])=>'<div class="xp-row"><span>'+label+'</span><strong>'+value+' XP</strong></div>').join('');
  document.querySelector('#spaceActivity').innerHTML=[['Gaming',data.gamingWins,Math.min(100,data.gamingWins*20)],['Study',fmtMinutes(data.focusSeconds),Math.min(100,data.focusMinutes*4)],['Music',data.musicQueue+data.musicPlaylists,Math.min(100,(data.musicQueue+data.musicPlaylists)*12)],['Community',data.communityPosts,Math.min(100,data.communityPosts*18)],['Tech',data.techProjects+' projects / '+data.techTasks+' done',Math.min(100,data.techXp)],['Art',data.artCompleted+' completed',Math.min(100,data.artXp)]].map(([label,value,progress])=>'<div class="space-row"><span>'+label+'</span><strong>'+value+'</strong><meter min="0" max="100" value="'+progress+'"></meter></div>').join('');
  const activity=[];
  if(data.gamingWins)activity.push('Won '+data.gamingWins+' arcade games.');
  if(data.focusMinutes)activity.push('Focused for '+fmtMinutes(data.focusSeconds)+' in Study Space.');
  if(data.musicQueue||data.musicPlaylists)activity.push('Saved '+(data.musicQueue+data.musicPlaylists)+' music items.');
  if(data.communityPosts)activity.push('Created or loaded '+data.communityPosts+' community posts.');
  if(data.techXp)activity.push('Earned '+data.techXp+' XP in Tech Space.');
  if(data.artXp)activity.push('Earned '+data.artXp+' XP in Art Space.');
  if(!activity.length)activity.push('Start using spaces to populate this dashboard.');
  document.querySelector('#activityList').innerHTML=activity.map((text)=>'<div class="activity-row"><span>'+text+'</span><strong>Synced</strong></div>').join('');
};
document.querySelector('#refreshDashboard').addEventListener('click',render);
const startLiveDashboardSync=()=>{
  let lastSnapshot='';
  const watchedKeys=['selestiaProfile','selestiaXP','selestiaWins','selestiaStudyFocusedSeconds','selestiaMusicQueue','selestiaMusicPlaylists','selestiaCommunityPosts','selestiaTechXP','selestiaTechProjects','selestiaTechTasks','selestiaTechResources','selestiaTechSprintSeconds','selestiaArtXP','selestiaArtCompleted','selestiaArtFreeCanvas'];
  const snapshot=()=>watchedKeys.map((key)=>key+':'+(localStorage.getItem(key)||'')).join('|');
  const sync=()=>{const nextSnapshot=snapshot();if(nextSnapshot===lastSnapshot)return;lastSnapshot=nextSnapshot;render();};
  sync();
  setInterval(sync,1000);
  window.addEventListener('storage',sync);
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync();});
};
startLiveDashboardSync();