const storage={projects:'selestiaTechProjects',tasks:'selestiaTechTasks',resources:'selestiaTechResources',notes:'selestiaTechNotes',chat:'selestiaTechChat',xp:'selestiaTechXP',sprintSeconds:'selestiaTechSprintSeconds'};
const $=(selector)=>document.querySelector(selector);
const safeJson=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
const saveJson=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const uid=()=>String(Date.now())+Math.random().toString(16).slice(2);
let projects=safeJson(storage.projects),tasks=safeJson(storage.tasks),resources=safeJson(storage.resources),messages=safeJson(storage.chat,[{id:uid(),name:'System',text:'Welcome to Tech Space. Add projects, save links, and start building.',system:true}]);
tasks = tasks.map((task) => ({ ...task, status: ['todo','doing','done'].includes(task.status) ? task.status : 'todo' }));
let techXp=Number(localStorage.getItem(storage.xp)||0),sprintSeconds=Number(localStorage.getItem(storage.sprintSeconds)||0),timer=null,remaining=25*60,total=remaining,running=false;
const escapeHtml=(value)=>String(value).replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const formatMinutes=(seconds)=>{const minutes=Math.floor(seconds/60);return minutes<60?minutes+'m':Math.floor(minutes/60)+'h '+(minutes%60)+'m'};
const formatTime=(seconds)=>String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');
const awardTechXp=(amount)=>{techXp+=amount;localStorage.setItem(storage.xp,String(techXp));renderStats()};
const renderStats=()=>{const doneCount=tasks.filter((task)=>task.status==='done').length,level=Math.floor(techXp/100)+1,levelXp=techXp%100;$('#techXpText').textContent=techXp+' XP';$('#techLevelText').textContent='Level '+level+' builder';$('#techXpFill').style.width=levelXp+'%';$('#projectCount').textContent=projects.length;$('#doneCount').textContent=doneCount;$('#resourceCount').textContent=resources.length;$('#sprintTime').textContent=formatMinutes(sprintSeconds)};
const renderProjects=()=>{$('#projectGrid').innerHTML=projects.length?projects.map((project)=>'<article class="project-card"><strong>'+escapeHtml(project.title)+'</strong><p>'+escapeHtml(project.stack)+'</p><div class="tag-row"><span class="tag">'+escapeHtml(project.status)+'</span><span class="tag">'+escapeHtml(project.date)+'</span></div><div class="card-actions"><button type="button" data-project-delete="'+project.id+'">Remove</button></div></article>').join(''):'<p class="micro-copy">No projects yet. Create your first build room.</p>'};
const taskLabels = { todo: 'Ready to start', doing: 'In progress', done: 'Completed' };
const taskActions = (task) => {
  const moves = ['todo', 'doing', 'done']
    .filter((status) => status !== task.status)
    .map((status) => '<button type="button" data-task-move="' + status + '" data-task-id="' + task.id + '">' + (status === 'todo' ? 'To do' : status === 'doing' ? 'Doing' : 'Done') + '</button>')
    .join('');
  return moves + '<button type="button" class="danger-action" data-task-delete="' + task.id + '">Remove</button>';
};
const renderTasks=()=>{document.querySelectorAll('.kanban-column').forEach((column)=>{const status=column.dataset.column,list=column.querySelector('.task-list'),filtered=tasks.filter((task)=>task.status===status);list.innerHTML=filtered.length?filtered.map((task)=>'<article class="task-card '+task.status+'"><strong>'+escapeHtml(task.title)+'</strong><span>'+taskLabels[task.status]+'</span><div class="task-actions">'+taskActions(task)+'</div></article>').join(''):'<p class="micro-copy">Empty</p>'})};
const renderResources=()=>{$('#resourceList').innerHTML=resources.length?resources.map((resource)=>'<article class="resource-item"><div><strong>'+escapeHtml(resource.title)+'</strong><a href="'+escapeHtml(resource.url)+'" target="_blank" rel="noreferrer">'+escapeHtml(resource.url)+'</a></div><button type="button" data-resource-delete="'+resource.id+'">Remove</button></article>').join(''):'<p class="micro-copy">Save docs, tutorials, repos, or videos here.</p>'};
const renderChat=()=>{$('#chatFeed').innerHTML=messages.map((message)=>'<div class="message'+(message.system?' system':'')+'"><strong>'+escapeHtml(message.name)+'</strong>'+escapeHtml(message.text)+'</div>').join('');$('#chatFeed').scrollTop=$('#chatFeed').scrollHeight};
const renderTimer=()=>{$('#timerDisplay').textContent=formatTime(remaining);$('#timerFill').style.width=total?((total-remaining)/total)*100+'%':'0%';$('#sprintState').textContent=running?'Running':'Idle'};
const renderAll=()=>{renderStats();renderProjects();renderTasks();renderResources();renderChat();renderTimer()};
$('#projectForm').addEventListener('submit',(event)=>{event.preventDefault();projects.unshift({id:uid(),title:$('#projectTitle').value.trim(),stack:$('#projectStack').value.trim(),status:$('#projectStatus').value,date:new Date().toLocaleDateString()});saveJson(storage.projects,projects);event.target.reset();awardTechXp(15);renderProjects()});
$('#projectGrid').addEventListener('click',(event)=>{const id=event.target.dataset.projectDelete;if(!id)return;projects=projects.filter((project)=>project.id!==id);saveJson(storage.projects,projects);renderProjects();renderStats()});
$('#taskForm').addEventListener('submit',(event)=>{event.preventDefault();const title=$('#taskTitle').value.trim();if(!title)return;tasks.unshift({id:uid(),title,status:$('#taskStatus').value});saveJson(storage.tasks,tasks);event.target.reset();awardTechXp(8);renderTasks();renderStats()});
$('#kanbanBoard').addEventListener('click',(event)=>{const deleteId=event.target.dataset.taskDelete;if(deleteId){tasks=tasks.filter((task)=>task.id!==deleteId);saveJson(storage.tasks,tasks);renderTasks();renderStats();return;}const id=event.target.dataset.taskId,status=event.target.dataset.taskMove;if(!id||!status)return;const task=tasks.find((item)=>item.id===id);if(!task)return;const wasDone=task.status==='done';task.status=status;saveJson(storage.tasks,tasks);if(status==='done'&&!wasDone)awardTechXp(12);renderTasks();renderStats()});
$('#resourceForm').addEventListener('submit',(event)=>{event.preventDefault();resources.unshift({id:uid(),title:$('#resourceTitle').value.trim(),url:$('#resourceUrl').value.trim()});saveJson(storage.resources,resources);event.target.reset();awardTechXp(10);renderResources()});
$('#resourceList').addEventListener('click',(event)=>{const id=event.target.dataset.resourceDelete;if(!id)return;resources=resources.filter((resource)=>resource.id!==id);saveJson(storage.resources,resources);renderResources();renderStats()});
$('#saveNote').addEventListener('click',()=>{localStorage.setItem(storage.notes,$('#codeNotes').value);$('#noteStatus').textContent='Saved just now.';awardTechXp(5)});
$('#chatForm').addEventListener('submit',(event)=>{event.preventDefault();messages.push({id:uid(),name:$('#chatName').value.trim()||'Builder',text:$('#chatInput').value.trim()});messages=messages.slice(-50);saveJson(storage.chat,messages);$('#chatInput').value='';awardTechXp(3);renderChat()});
$('#clearProjects').addEventListener('click',()=>{projects=[];saveJson(storage.projects,projects);renderProjects();renderStats()});$('#clearTasks').addEventListener('click',()=>{tasks=[];saveJson(storage.tasks,tasks);renderTasks();renderStats()});$('#clearResources').addEventListener('click',()=>{resources=[];saveJson(storage.resources,resources);renderResources();renderStats()});$('#clearChat').addEventListener('click',()=>{messages=[{id:uid(),name:'System',text:'Chat cleared. Start a fresh tech room.',system:true}];saveJson(storage.chat,messages);renderChat()});
const resetTimerValues=()=>{total=Math.max(1,Number($('#sprintMinutes').value||25))*60;remaining=total;renderTimer()};
$('#startSprint').addEventListener('click',()=>{if(running)return;if(remaining<=0)resetTimerValues();running=true;renderTimer();timer=setInterval(()=>{remaining-=1;if(remaining<=0){clearInterval(timer);running=false;remaining=0;sprintSeconds+=total;localStorage.setItem(storage.sprintSeconds,String(sprintSeconds));awardTechXp(Math.max(10,Math.round(total/60)*2))}renderTimer()},1000)});
$('#pauseSprint').addEventListener('click',()=>{clearInterval(timer);running=false;renderTimer()});$('#resetSprint').addEventListener('click',()=>{clearInterval(timer);running=false;resetTimerValues()});$('#sprintMinutes').addEventListener('change',()=>{if(!running)resetTimerValues()});
$('#codeNotes').value=localStorage.getItem(storage.notes)||'';renderAll();